FROM tensorflow/tensorflow:1.14.0-py3

ENV LANG=C.UTF-8

ENV FLASK_APP=src/flask_conditional_samples.py

RUN mkdir /gpt-2
WORKDIR /gpt-2
ADD . /gpt-2

RUN pip3 install -r requirements.txt

# RUN python3 download_model.py 124M
# RUN python3 download_model.py 355M
# RUN python3 download_model.py 774M
# RUN python3 download_model.py 1558M

RUN pip3 install flask

CMD flask run --host='0.0.0.0' -p 8000
